project_id = "egwishjwlrhhumtnkrfo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54324

[realtime]
enabled = true
port = 54325

[functions.ai-content-moderator]
verify_jwt = true

[functions.ai-description-enhancer]
verify_jwt = true

[functions.ai-thumbnail-generator]
verify_jwt = true

[functions.ai-illustration-generator]
verify_jwt = true

[functions.ai-text-translator]
verify_jwt = true