name: 🤖 Build AAB - arm64-v8a

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧬 Cloner le dépôt
        uses: actions/checkout@v3

      - name: ⚙️ Configurer Java & Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: 📥 Récupérer le keystore (.jks)
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/afrikoin-release-key.jks

      - name: 📦 Mettre à jour Gradle pour ABI arm64-v8a
        run: |
          sed -i '/defaultConfig {/,/}/s/ndk {/ndk {\n            abiFilters "arm64-v8a"/' android/app/build.gradle

      - name: 🔨 Générer le .aab
        run: ./gradlew bundleRelease -p android

      - name: 📤 Exporter le .aab en tant qu’artifact
        uses: actions/upload-artifact@v4
        with:
          name: afrikoin-arm64-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
