# cloudbuild.yaml — Build Docker, push vers Artifact Registry, puis déploie sur Cloud Run

substitutions:
  _AR_HOSTNAME: 'europe-west1-docker.pkg.dev'
  _AR_PROJECT_ID: 'afrikoin-deploy'
  _AR_REPOSITORY: 'cloud-run-source-deploy'
  _DEPLOY_REGION: 'europe-west1'
  _PLATFORM: 'managed'
  _SERVICE_NAME: 'afrikoin-vibes-connect'

# Image taggée par SHA du commit (valable pour rollback facile)
images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8   # Ajuste si besoin
  substitution_option: 'ALLOW_LOOSE'

steps:
  # 1) Build Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:${COMMIT_SHA}'
      - '.'

  # 2) Push vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:${COMMIT_SHA}'

  # 3) Déploiement Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        gcloud run deploy "$_SERVICE_NAME" \
          --image "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:${COMMIT_SHA}" \
          --region "$_DEPLOY_REGION" \
          --platform "$_PLATFORM" \
          --allow-unauthenticated
