// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxmkerlafvgiwqlaxkiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4bWtlcmxhZnZnaXdxbGF4a2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0Mjk3OTcsImV4cCI6MjA4NDAwNTc5N30.e09ukWRyOZ2kdgvBqpJuYSOY50jcZJhVk2qdO25r8Ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});