// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egwishjwlrhhumtnkrfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnd2lzaGp3bHJoaHVtdG5rcmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTI4NDQsImV4cCI6MjA2Nzc2ODg0NH0.6w-G_nOuz-HdrFIKJpwA5ChQvSD4cDTfmvG5K0hh9o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});