// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diglkmdsxpfimylshnmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZ2xrbWRzeHBmaW15bHNobm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNTU5OTIsImV4cCI6MjA5MDgzMTk5Mn0.u1ViCxg73iNia35kYMFgSdybvyXqvaTpIo8WdS_dXQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}) as any;