name: Android CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Make Gradle wrapper executable
      run: chmod +x android/gradlew
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle cache
      uses: gradle/actions/setup-gradle@v3

    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test --if-present
      
    - name: Lint code
      run: npm run lint --if-present
      
    - name: Build web app
      run: npm run build
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Check Android build
      working-directory: android
      run: ./gradlew assembleDebug --stacktrace
        
    - name: Run Android unit tests
      working-directory: android
      run: ./gradlew testDebugUnitTest --stacktrace
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-test-results
        path: android/app/build/test-results/